### ISSUE TITLE
Contribute using GitHub workflow is different for non collaborators

### ISSUE THREAD

**Issue by MIchaelMainer** [OfficeDev/VBA-content#11]
https://github.com/OfficeDev/VBA-content/blob/master/CONTRIBUTING.md

In step 5 of Contribute using GitHub, it states: ‘Select Create a new branch for this commit and start a pull request radio button.’ Can people who aren’t a collaborator do branch operations on a repo? I didn’t have that impression. My impression is that they would need to fork the repo to make the pull request.  Please review this step and verify that this will work for non project collaborators.

**Comment by Lauragra** [comment]
This has been fixed - thanks!
