### ISSUE TITLE
Missing information in Custom Document Properties article

### ISSUE THREAD

**Issue by cindymeister** [OfficeDev/VBA-content#123]
VBA-content / Office-Shared-VBA / articles / 80738562-8b0b-33f1-3dfa-0d66b1844ef7.md

The LinkSource information is incomplete. WHAT are valid link sources for each application? Please give code examples that actually WORK.

**Comment by laschultz** [comment]
Thanks for your suggestion to make the VBA docs better. Links were added to the property descriptions that make it more clear how to use the code example in this topic. In addition, we've added an example of a valid LinkSource property. Let us know if we can be of further assistance.

**Comment by cindymeister** [comment]
Thank you for your comment. I'm not seeing the changes you mention, looking at https://msdn.microsoft.com/EN-US/library/office/ff862806.aspx. Could you please provide a link?

**Comment by laschultz** [comment]
Hi Cindy,
MSDN updates will appear after the nightly build at midnight tonight. In the meantime, you can see them on GitHub at VBA-content / Office-Shared-VBA / articles / 80738562-8b0b-33f1-3dfa-0d66b1844ef7.md. I'll let you know when MSDN is updated. Thanks!
