### ISSUE TITLE
Range.RemoveDuplicates does not specify default behavior 

### ISSUE THREAD

**Issue by degustaf** [OfficeDev/VBA-content#143]
[Range.RemoveDuplicates Method](https://github.com/OfficeDev/VBA-content/blob/master/Excel-VBA/articles/0e74bde2-08b3-898d-0b30-53de911bd7e9.md)

columns is an optional argument to this method, but no information is given as to what happens if the argument is not supplied.

**Comment by laschultz** [comment]
Changed to "Required", because this method could not be executed without a specified range.
