### ISSUE TITLE
If the user does SAVE AS and then hits cancel, Excel still sets the CANCEL boolean to FALSE.

### ISSUE THREAD

**Issue by scrybbler** [OfficeDev/VBA-content#150]
This is my first post here so maybe I'm doing this wrong but...

If the user chooses File > Save As and then hits cancel, Excel still sets the CANCEL boolean to *FALSE*. However, if the user makes changes, quits, and declines to save changes, Excel correctly sets the CANCEL boolean to True.

Perhaps I am using the CANCEL boolean the wrong way. *If it is merely a switch that is provided to us to allow us to disable a save action, then I am using it the wrong way.* (The description of the boolean at https://msdn.microsoft.com/en-us/library/office/ff840057.aspx does say it is "False when the event occurs" which implies that it is set to True when the event does not occur. Perhaps the docs should clarify which event.)

Even if I am using it the wrong way, it does seem like there's a need here for a flag that would indicate the difference between a user *starting* the save process and a user actually *approving* the save action because those create materially different outcomes.

**Comment by laschultz** [comment]
Excel is behaving as expected in this case. The boolean is set to FALSE only when there are changes that need to be saved in the workbook. If the user chooses Save As when there are no changes needing to be saved, Excel will still set the CANCEL boolean to FALSE. In order to clarify the point that you raised, I updated the SaveAsUI parameter description to read "True if the Save As dialog box will be displayed due to changes made that need to be saved in the workbook".

**Comment by scrybbler** [comment]
Thank you laschultz!

Forgive me if this is a stupid question, but is the Cancel boolean serving two purposes -- allowing VBA to stop a save action from occurring (as in the Holy Macro example on https://msdn.microsoft.com/en-us/library/office/ff840057.aspx?f=255&MSPPError=-2147217396) *and* signalling when there are changes needing to be saved in the workbook?

Is there a way to tell when a user manually triggers a Save As action (for both cases: with changes needing to be saved, and no changes pending) and then changes their mind and cancels away the Save As dialog box?

**Comment by laschultz** [comment]
Dear scrybbler, Thanks for your comment. Your question is a good one. This GitHub forum is specifically for suggested changes and additions to the VBA documentation. For issues with code, we suggest that you post your question on one of these forums: 
  https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=isvvba
http://stackoverflow.com/questions/tagged/excel-vba
