### ISSUE TITLE
Workbook.SaveCopyAs Method (Excel) returns Run-time error '1004'

### ISSUE THREAD

**Issue by ognjanovic** [OfficeDev/VBA-content#151]
It is Office 2016 Mac OS edition issue.
````
Private Sub Workbook_BeforeSave(ByVal SaveAsUI As Boolean, Cancel As Boolean)
    Dim FilenameStr As String
    FilenameStr = Sheet1.Range("F11").Value
    FilenameStr = ActiveWorkbook.Path & "/" & FilenameStr & "_" & Sheet1.Range("I5").Value
````
Or this as an alternative for the previous line
````
    FilenameStr = FilenameStr & "_" & Sheet1.Range("I5").Value
````
At this point I get the FilenameStr like this
/Users/myusername/somedir/123456789_20130531-002
````
    ActiveWorkbook.SaveCopyAs (FilenameStr & ".xls")
    Cancel = True
End Sub
```
This is the error I'm getting
**Run-time error '1004': Cannot access read-only document 123456789_20130531-002.xls**

The file doesn't exist and has to be created, but everythig worked back in Office 2011.

**Comment by laschultz** [comment]
Thanks for your comment. Your feedback is appreciated. This GitHub forum is specifically for suggested changes and additions to the VBA documentation. We recently updated the SaveAsUI topic, so check to see if this change addresses your issue. Also try setting Cancel = False. For other code issues, we suggest that you post your question to one of these forums: 
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=isvvba
http://stackoverflow.com/questions/tagged/excel-vba
