### ISSUE TITLE
Selection.Collapse Method (Word): constants not defined (C++)

### ISSUE THREAD

**Issue by dentonlt** [OfficeDev/VBA-content#153]
(I'm on VS15 Community, v14.0.x Update 1).

This article directs developers to use the WdCollapseDirection constants, but these are not defined in the C++ headers.

Alternatively, wdCollapseEnd = 1, wdCollapseStart = 0.

A Word automation example/snippet:

```
// This uses AutoWrap() from Solution2.cpp in the CppAutomateWord sample project at
// https://code.msdn.microsoft.com/office/CppAutomateWord-14799966

IDispatch *o_Selection; // set this to your Selection object ...
...
	VARIANT param, ret;
		VariantInit(&param);
		VariantInit(&ret);
	param.vt = VT_INT;
	param.lVal = 0; // 0 = end, 1 = start
	HRESULT hr = AutoWrap(DISPATCH_METHOD, &ret, o_Selection, L"Collapse", 1, param);
	if (FAILED(hr)) {
			wprintf(L"msl_IDispatch Selection::Compress failed with error 0x%x08l.\n", hr);
			return E_FAIL;
	}
...
```

**Comment by v-stnel** [comment]
Sorry about the delay in getting back to you, but can you give me some more information on this?

**Comment by v-stnel** [comment]
Thanks for your comments. Could you tell me where you obtained the C++ headers so that I can track this more closely.  Thanks.

**Comment by v-stnel** [comment]
Closed. I was not able to determine where the C++ headers were obtained.
