### ISSUE TITLE
Problems with TextRange2

### ISSUE THREAD

**Issue by stormraiser** [OfficeDev/VBA-content#16]
I'm writing an add-in for PowerPoint 2013 with C#.
I think here in bce672a4-b108-b223-7e65-71f07d7f4197.md the return type of TextRange method should be TextRange2. It took me some time to figure this out and it confused me. Is that an error in the document or C# and VBA are different? TextRange2 is not even listed in the index.
And I guess probably there are errors elsewhere where xxx should be xxx2.

**Comment by v-stnel** [comment]
Thanks for pointing out this issue. I have chanced the return value for TextRange property and added the TextRange2 object to the TOC. The information on MSDN is correct and we will be updating GitHub shortly.
