### ISSUE TITLE
access

### ISSUE THREAD

**Issue by dephoen1x** [OfficeDev/VBA-content#162]
does any know how to increase the short text 255 max word without going to long text. The software would not allow me to increase the text and it erases what every is inputted into the data base when you you try switching to long text.

**Comment by laschultz** [comment]
Hi dephoen1x,

Thanks for your question. This GitHub site is for suggesting changes and additions to the VBA documentation. For answers to your question about the 255 character limit, please see 
http://stackoverflow.com/questions/1065993/has-windows-7-fixed-the-255-character-file-path-limit.

**Comment by dephoen1x** [comment]
Sorry Lori.

On Fri, Jan 15, 2016 at 3:30 PM, Lori Schultz Goff <notifications@github.com

**Comment by laschultz** [comment]
No worries. I hope this information is helpful. A related article is at http://stackoverflow.com/questions/1880321/why-does-the-260-character-path-length-limit-exist-in-windows

**Comment by dephoen1x** [comment]
Thanks u.
