### ISSUE TITLE
Catching events doesn't work as advertised

### ISSUE THREAD

**Issue by Darker** [OfficeDev/VBA-content#17]
I have a problem with this basic tutorial: https://github.com/OfficeDev/VBA-content/blob/master/Outlook-VBA/articles/560bb264-05d0-dbc6-39c2-b95b12f50ed9.md

Also hosted on msdn: https://msdn.microsoft.com/en-us/library/bb206733.aspx

I produced following code, placed in `ThisOutlookSession`:

    Dim WithEvents myOlBar As Outlook.OutlookBarPane
    
    Private Sub Application_NewMail()
        MsgBox "New mail"
    End Sub
    Private Sub myOlBar_BeforeNavigate(ByVal Shortcut As OutlookBarShortcut, Cancel As Boolean)
        MsgBox Shortcut.Name
    End Sub
    
    Private Sub Application_Startup()
     Set myOlBar = Application.ActiveExplorer.Panes(1)
    End Sub

I enabled macros:

![image description](http://i.stack.imgur.com/NxGmN.png)

I confirmed that I allow macros after outlook restart:

![image description](http://i.stack.imgur.com/1ezHX.png)

Still I get no effect whatsoever. However if I put some debug code in application startup callback, it works - I can print Hello world on startup:

    Private Sub Application_Startup()
       MsgBox "Hello world!"
    End Sub

![image description](http://i.stack.imgur.com/CrGPr.png)

So why is startup the only callback that works?

**Comment by chbighammsft** [comment]
Thanks for your comment. You can use GitHub to make changes and additions to the VBA documentation, but for issues with your code we suggest that you post your question on one of these forums.

https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=outlookdev
http://stackoverflow.com/questions/tagged/outlook
