### ISSUE TITLE
AutoFormatAsYouTypeApplyFirstIndents not working

### ISSUE THREAD

**Issue by kboomhouwer** [OfficeDev/VBA-content#170]
When I run the following code, it is not changing the "Set left- and first-indent with tabs and backspaces" under Options > Proofing > AutoCorrect Options... > AutoFormat As You Type

objOptions.AutoFormatAsYouTypeApplyFirstIndents = FALSE

Is this the correct object name?

**Comment by kboomhouwer** [comment]
Here is the script (in a .txt file) that I'm trying to run. Everything else works fine except for AutoFormatAsYouTypeApplyFirstIndents.
[MS_Word_Advanced_Options.txt](https://github.com/OfficeDev/VBA-content/files/123413/MS_Word_Advanced_Options.txt)

**Comment by laschultz** [comment]
Hi kboomhouwer,
Thanks for your question. You can use GitHub to make changes and additions to the VBA documentation. For issues with your code, we suggest you post to one of these forums:
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=worddev
http://stackoverflow.com/questions/tagged/word
laschultz
