### ISSUE TITLE
Unit missing in .Height and .Width properties

### ISSUE THREAD

**Issue by Trallali** [OfficeDev/VBA-content#173]
Would be nice to know if e.g. .Width is in twips or pixel or meter :-) on all objects: Application, Table, Range, ...

**Comment by v-stnel** [comment]
Thank you for the input. Could you tell me which object you are referring to, such as the Application.Width parameter?

**Comment by v-stnel** [comment]
Thank you for your input on these properties. I added the units to the Application.Height property (Word), however all the other Height and Width properties had the correct units. If you found other properties, please add a link to those properties and I will look at them as well.

**Comment by Trallali** [comment]
@v-stnel: There is a lot of units missing in **Word**:
**Shape**.height/width, [link](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/3738d3b8-c412-7b42-b430-5082e822eab4.md)
**Row**.Height/Width [link](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/37586889-891d-5fb4-7f27-d590b92ba77b.md)
**Frameset** [link](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/4f577980-30ca-540f-932a-a707ab6d8b5f.md)
**Window** [link](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/9b96ac83-57cc-4cb2-768b-2b5012c49bbc.md)

and almost all others (Cells, ProtectedView, ...) . Download the chm, search for "height", click through.

A reference to the `PointsTo<X>` and `<X>ToPoints` functions would be helpful where appropriate, right now only in Word as far as I see.

The Excel units are ok. There is a spelling error in the [window.heigth](https://github.com/OfficeDev/VBA-content/blob/master/Excel-VBA/articles/abfbd7ee-a983-cfb1-51c3-09159c8ba08c
