### ISSUE TITLE
Using .location with Excel 2007

### ISSUE THREAD

**Issue by jcaldw737** [OfficeDev/VBA-content#183]
This is more of a question than an issue..  I tried .location in an Excel 2007 workbook and it works just fine on my laptop, but my users got an error on it  1004

The specified dimension is not valid for the current chart type.

Am I dead in the water?

Thanks!

**Comment by cronos2546** [comment]
What did they try and what did you try for the specified method?

**Comment by jcaldw737** [comment]
Actually it is the same code - in a macro that I distributed to them in a workbook.

  Dim objChtDupl As Object  
  Set objChtDupl = Sheets("I Chart").ChartObjects(1).Duplicate 
  Sheets("Layout").Select
    With ActiveSheet  
       objChtDupl.Chart.Location xlLocationAsObject, .Name

Works fine on my laptop running Excel 2007 with Windows 8, but fails on the last line above on two user laptops with the Excel 2007 with Windows 7

Run-time error 1004  The specified dimension is not valid for the current chart type.

They get the duplicated chart but it is still on the first sheet.

Thanks again!

**Comment by jcaldw737** [comment]
Turns out the user is running Excel 2013.  We are now trying a simple xlsm with Location in it and will report the results when we have more of them.

Thanks again!

**Comment by jcaldw737** [comment]
Location works fine for  us with a simple example.  We are having trouble using it in a "large" macro that dates back to at least 1994.  Let's assume our code has some issues, perhaps with event actions.  We have another solution to keep us going.  Let's close this puppy.
