### ISSUE TITLE
Version-related contributions

### ISSUE THREAD

**Issue by sixareen** [OfficeDev/VBA-content#185]
I am interested in contributing to this repository, partly to document Mac/Windows differences - as you may know, most of the Mac VBA-specific documentation disappeared from the web a couple of years ago.

However, 
 a. I see that there is little or no version-specific information in the entries for objects, properties etc., and I don't see an established convention for specifying which version contains what.

 b. it is not completely obvious which versions you are targetting. I would guess that Microsoft's focus is on the 2016 versions on Windows and Mac, and probably earlier supported Windows versions, but Mac developers have not had access to reliable 2011 documentation for some time, and discovery of what is and is not in Office for Mac VBA 2016 is largely a matter of trial and error, given the current state of the VBA IDE. IMHO documentation of this kind should really aim to be as comprehensive a reference as possible, even documenting unsupported versions if someone is willing to contribute the information.

 c. If you are syncing the material with MSDN, there could well be a serious problem where different parts of the documentation are in very different states (e.g., some pointing out Windows/Mac differences, and others not).

Please advise!

**Comment by cjboorman** [comment]
Hi Sixareen,

Thanks for volunteering to help! We'd be happy to accept your contribution, and would appreciate it if you would add any mac-specific information in a note, and point out which version you are referring to.
