### ISSUE TITLE
Read Only error when merging excel files

### ISSUE THREAD

**Issue by harrydawg** [OfficeDev/VBA-content#186]
When I run the code it says there is a compile error: cant assign to read-only property

Sub GetSheets()
Path = "C:\Users\H\Desktop\AMORT"
Filename = Dir(Path & " hi.xls")
  Do While Filename <> ""
  Workbooks.Open Filename:=Path & Filename, ReadOnly:=True
     For Each Sheet In ActiveWorkbook.Sheets
     Sheet.Copy After:=ThisWorkbook.Sheets(1)
  Next Sheet
     Workbooks(Filename).Close
     Filename = Dir()
  Loop
End Sub

**Comment by sixareen** [comment]
I don't know why you get a compile error, but removing the space before the "hi" in " hi.xls" might get you one step further in your effort to debug your code.

**Comment by laschultz** [comment]
harrydawg,
Thanks for your question. I see that sixareen responded to your initial inquiry. This site is for suggesting changes and additions to the Office VBA documentation. For issues with your code, we suggest that you post your question to one of these forums:
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=excel
http://stackoverflow.com/questions/tagged/excel
Office Scale Team
