### ISSUE TITLE
WindowBeforeRightClick event has been fixed for Word 2016

### ISSUE THREAD

**Issue by snoqwalker** [OfficeDev/VBA-content#188]
In a previous revision to the WindowBeforeRightClick event for Word 2016, you had added the notation "The WindowBeforeRightClick event is not available for Word 2016."  This was correct at the time, because the event was broken and unavailable to Word 2016 developers for many months. But this was just recently fixed by Microsoft, so the event DOES now work as expected with Word 2016.

**Comment by cjboorman** [comment]
Per VBA content Issue #188 - WindowBeforeRightClick event has been fixed for Word 2016: Removed the remark "The  **WindowBeforeRightClick** event is not available for Word 2016." because this feature has now been fixed.
