### ISSUE TITLE
Reference doesn't work  Office-Mac-VBA.

### ISSUE THREAD

**Issue by asith-w** [OfficeDev/VBA-content#189]
is there any working  references for  Office-Mac-VBA. any of link does not work
ex : 
https://github.com/OfficeDev/VBA-content/blob/master/Office-Mac-VBA/articles/AppleScriptTask.md

**Comment by sixareen** [comment]
https://github.com/OfficeDev/VBA-content/blob/master/Office-Mac-VBA/AppleScriptTask.md ?

**Comment by Lauragra** [comment]
Thank you; the link provided is the right link to the topic. You can also browse the content on MSDN, here: https://msdn.microsoft.com/en-us/library/mt654019.aspx .
