### ISSUE TITLE
Remark in MailItem.ConversationID topic is stripped of version number inappropriately

### ISSUE THREAD

**Issue by angelgolfer-ms** [OfficeDev/VBA-content#190]
The topic is at https://msdn.microsoft.com/en-us/library/ff867895.aspx.

In the Remarks section, the phrase "If the MailItem object is created in a version of Microsoft Outlook earlier than Outlook, or if..." is missing a version indicator for "Outlook". The version is Outlook 2010 - ConversationID was introduced in Outlook 2010.
![mailitemconversationid topic error](https://cloud.githubusercontent.com/assets/12191822/14401114/ce9b5db6-fdba-11e5-894e-c5fc3aa5b562.png)

**Comment by cjboorman** [comment]
Fifteen topics were affected by this issue. I've fixed all fifteen of them.

**Comment by cjboorman** [comment]
...and thanks for bringing this to our attention!j  :-)
