### ISSUE TITLE
Cannot find all the Microsoft Excel VBA classes - where are they defined?

### ISSUE THREAD

**Issue by danbromberg** [OfficeDev/VBA-content#194]
The Java Development Kit has a listing of all the Java classes, containing the Java defined keyword elements and functions.
I assumed that the Excel VBA would have a similar listing of all the Microsoft defined classes but am unable to find such a repository. Since writing a macro using reserved words of Excel objects is common, where do I find such a complete listing that I may refer to?
Thanks,
Dan

**Comment by laschultz** [comment]
Hi Dan, thanks for your inquiry. Can I ask which version of Excel are you using? To answer your question, you can download an offline version in CHM format here: http://www.microsoft.com/en-us/download/details.aspx?id=40326.
Lori, Office Scale Team

**Comment by danbromberg** [comment]
Lori,
   The 'chm' file is exactly what I was looking for.
   Don't know why I couldn't find it but you did - so thanks very much!
Dan

**Comment by laschultz** [comment]
Dan,
Great! I'm glad this is what you were looking for!
Lori
