### ISSUE TITLE
.save changes the current directory to documents area even if document is being saved elsewhere

### ISSUE THREAD

**Issue by RN9** [OfficeDev/VBA-content#195]
You need to at least document that using .save will cause the current directory to change to where your documents are stored even if the file you are saving is elsewhere.   This causes to any code that relies on relative paths.  You must save off the current director and use chdir and chdrv (chdir will not change the current drive even if it is in the chdir command)  to restore

**Comment by cjboorman** [comment]
RN9, what is the context of what you are doing? Which API are you using?

**Comment by RN9** [comment]
I am using the MS word VBA macro to save the active document 
                    AutoSaveStartTime = Timer
                    'Save current directory and restore after save
                    CurrentDirectory = CurDir$
                    'Prevent request to save normal template changes
                    'Changes the status of the Normal template  and CTRS_Styles to unchanged.
                    NormalTemplate.Saved = True
                    ' Prevent ActiveDocument from reporting that it has changed
                    ActiveDocument.AttachedTemplate.Saved = True
                    ActiveDocument.TrackRevisions = False
                    If ActiveDocument.Revisions.Count >= 1 Then
                        ' Avoid Tracked changes warning
                        ActiveDocument.AcceptAllRevisions
                    End If
                    ActiveDocument.Save                         'Save the assembled document being built
                    ' CurrentDirectory is now the documents area for user
                    BOM_Command = BOM_Command + " Auto-Saved"   'Build status message
                    ChDir CurrentDirectory                      'Restore directory afer save
                    'ChDir does not restore current drive
                    ChDrive Left$(CurrentDirectory, 1)
                    'Reset counter for includes since last save

**Comment by cjboorman** [comment]
I wrote a little test program to try to reproduce the problem you're experiencing, and I learned a couple of things. The CurDir() function initially points to the user's MyDocuments folder (%USERPROFILE%\Documents). When you save your document for the first time, you must use "SaveAs", and if you save it to another folder, then CurDir() changes and points to the new location.


```
Sub TestCurDir()
'
' TestCurDir Macro
'
'
    Dim CurrentDirectory As String
    
    CurrentDirectory = CurDir()
    
    MsgBox "The current directory is " & CurrentDirectory
    
    ActiveDocument.Save
    
    MsgBox "The current directory is " & CurDir()
    
End Sub
```

**Comment by RN9** [comment]
Thanks for the test.  When I run my code the directory is set to where a batch file that kicks off the macro runs from.   Current directory before agrees.   After the save it does not but it is saved where I expect to be.   
The document is saved intially  with     ActiveDocument.SaveAs FileName:=AsmFileName             '   Save assembly before adding parts to it

Every thing I need is accessed via relative addressing: go up one directory from where you are and then look for directory containing file.   If current directory changes to the user area for any reason the code stops working.

**Comment by laschultz** [comment]
Thanks for your question. This GitHub site is for suggesting changes and additions to the Office VBA documentation. For issues with your code, we suggest that you post your question on one of these forums:
Example (Office)
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=officedev
http://stackoverflow.com/questions/tagged/vba
