### ISSUE TITLE
Special characters in code samples are HTML encoded

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#200]
The VBA and HTML/VBScript examples include code blocks escaped with \`\`\` code blocks, which result in `<pre>` tags in GitHub renderings. That means that encoding inside the code blocks should not be HTMLEncoded.

**VBA Example**
This [file](https://github.com/OfficeDev/VBA-content/blob/master/Excel-VBA/articles/fc61a9c1-d651-502a-c8d4-d6a570898191.md) has ampersand `&` concatenation operators, but they've been HTML encoded.

```vb
.Cells(lnRow, 2).Value = "'" &amp; lnCount &amp; "-" &amp; lnPages 
```
The line should read:
```vb
.Cells(lnRow, 2).Value = "'" & lnCount & "-" & lnPages 
```

**HTML example**
For example, this [file](https://raw.githubusercontent.com/OfficeDev/VBA-content/6bdb4edc01c0a9f06e454ccd9cdf1a1175b0288e/Access-VBA/articles/bc22a6c4-b9d4-ad38-d802-4790ff3262a6.md)'s HTML include `&gt;` HTML entities, but they're corrupted by being HTMLEncoded:

```html
<OPTION VALUE="&amp;gt;">&amp;gt;</OPTION><OPTION VALUE="&amp;lt;">&amp;lt;</OPTION>
```

The line should read as:

```html
<OPTION VALUE="&gt;">&gt;</OPTION><OPTION VALUE="&lt;">&lt;</OPTION>
```
I haven't checked every code example, but this problem would seem to exist on all pages that involve code samples.

Copying code samples into a VB Editor results in corrupt code.

**Comment by laschultz** [comment]
ThunderFrame, thank you for point out this issue. Your contributions help improve the technical accuracy of our documentation. This formatting error happened when we converted our VBA Reference to GitHub. We are fixing these formatting issues in the coming weeks, so stay tuned. Thank you!
