### ISSUE TITLE
Usage guidelines omit spaces

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#201]
**VBA-Content** usage expressions include underscore characters
```vb
_result_**=**_expression1_**&amp;**_expression2_
```
which render, without spaces, as:

_result_**=**_expression1_**&amp;**_expression2_

But the online help page [here](https://msdn.microsoft.com/en-us/library/office/gg264104.aspx) uses this HTML, which includes spaces:

```html
<p> <em>result </em> <strong>= </strong> <em>expression1 </em> <strong>&amp; </strong> <em>expression2</em> </p>
```
which renders, including spaces, as:
<p> <em>result </em> <strong>= </strong> <em>expression1 </em> <strong>&amp; </strong> <em>expression2</em> </p>

The true VBA syntax should include spaces, so the project markdown should use:
```vb
_result_ **=** _expression1_ **&amp;** _expression2_
```
which will render as:

_result_ **=** _expression1_ **&amp;** _expression2_

**Comment by laschultz** [comment]
ThunderFlame, Thank you for your contribution. I've updated the topics affected by this spacing issue.
