### ISSUE TITLE
Asterisks are not Markdown escaped

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#202]
Pages that use an asterisk character (\*) do not have the asterisk character escaped, which corrupts the markdown.
See [this example](https://github.com/OfficeDev/VBA-content/blob/a8d2afc189fb9a6dcc4f8322fd38eef36ab74381/Excel-VBA/articles/ce225526-f4b9-8b6a-0b19-21bea06cd728.md)

To escape an asterisk, the asterisk should be escaped with a backslash \\

**Comment by laschultz** [comment]
ThunderFrame, Thanks for catching this. Your contributions help improve the technical accuracy of our documentation.
