### ISSUE TITLE
Links to Glossary pages often omit a leading space

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#203]
There are [930](https://github.com/OfficeDev/VBA-content/search?utf8=%E2%9C%93&q=%28b8bdf64f-5920-1ae9-16d0-b26d09524a30.md%29) pages with links to the glossary. Many of those links are missing a leading space before the link.

For example
[Properties Window Command (View Menu)](https://github.com/OfficeDev/VBA-content/blob/a8d2afc189fb9a6dcc4f8322fd38eef36ab74381/Language-Reference-VBA/articles/6263cb7b-c692-2d9b-7d1e-c9258f47e656.md)
> Displays the  **Properties** window, which lists the design-time properties for a selected[form](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md), [control](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md), [class](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md), [project](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md) or[module](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md).

Notice the missing spaces before **form** and **module**, but *not* before **control**, **class** and **project**

And in this example
[Interface not valid for Implements](https://github.com/OfficeDev/VBA-content/blob/a8d2afc189fb9a6dcc4f8322fd38eef36ab74381/Language-Reference-VBA/articles/944e5139-44df-b07f-d594-c1d869a4c125.md)
> - The interface contains some element that can't be supported by Visual Basic. For example, Visual Basic has no equivalent to the unsigned long integer type, Visual Basic can't designate a [procedure](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md)[parameter](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md) as "out-only." Although Visual Basic supports the use of the underscore character (_) in Visual Basic[identifiers](b8bdf64f-5920-1ae9-16d0-b26d09524a30.md), it can't implement an interface that uses underscore characters in the names of its members. 

Notice the missing space before **parameter** and **identifiers**, but *not* before **procedure**

**Comment by laschultz** [comment]
ThunderFrame, Thank you for bringing this issue up. We have been aware of this spacing issue and are working to resolve it in as many topics as we can.
