### ISSUE TITLE
Some bold member names (and headings) have an unnecessary leading space

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#204]
For [example](https://github.com/OfficeDev/VBA-content/blob/a8d2afc189fb9a6dcc4f8322fd38eef36ab74381/Language-Reference-VBA/articles/d2303a41-d557-032c-c195-febde9029f8a.md)

>  **Settings**
The default setting for a control is a unique name based on the type of control. For example, CommandButton1 is the default caption for the first command button in a form.
 **Remarks**
The text identifies or describes the object with which it is associated. For buttons and labels, the  **Caption** property specifies the text that appears in the control. For **Page** and **Tab** objects, it specifies the text that appears on the tab.
If a control's caption is too long, the caption is truncated. If a form's caption is too long for the title bar, the title is displayed with an ellipsis.
The  **ForeColor** property of the control determines the color of the text in the caption.
>
> **Tip**  If a control has both the  **Caption** and **AutoSize** properties, setting **AutoSize** to **True** automatically adjusts the size of the control to frame the entire caption.

The **Settings**, **Remarks**, **Caption**, **ForeColor** and **Tip** keywords all have leading spaces, which usually results in 2 spaces, so while browsers won't usually render consecutive spaces, there's room for improvement in the underlying source, for situations where the leading space will be rendered unintentionally.

**Comment by laschultz** [comment]
ThunderFrame, Thanks for bringing this to our attention. We are addressing the extra/missing space issue for as many topics as we can.
