### ISSUE TITLE
Special characters have been replaced by question marks

### ISSUE THREAD

**Issue by ThunderFrame** [OfficeDev/VBA-content#207]
Some files contain multiple question marks, where, presumably, there was originally other characters that have been lost to encoding changes

It's not always clear what the `?` was originally, but in many cases, the `?` was an operator, so reinstating the correct character is both difficult and critical.

See [this](https://github.com/OfficeDev/VBA-content/blob/a8d2afc189fb9a6dcc4f8322fd38eef36ab74381/Excel-VBA/articles/e8940dd7-26c2-ae9b-1876-1c61afcea33d.md) example:

```
- Make sure that you are consistent about the units you use for specifying rate and nper. If you make monthly payments on a four-year loan at an annual interest rate of 12 percent, use 12%/12 for rate and 4*12 for  _Arg2_ . If you make annual payments on the same loan, use 12% for rate and 4 for _Arg2_ .
    
-  _Arg2_ , _Arg4_ , _Arg5_ , and type are truncated to integers.
    
- If rate ? 0,  _Arg2_ ? 0, or _Arg3_ ? 0, CumIPmt generates an error.
    
- If  _Arg4_ < 1, _Arg5_ < 1, or _Arg4_ > _Arg5_ , CumIPmt generates an error.
    
- If  _Arg6_ is any number other than 0 or 1, CumIPmt generates an error.
```

**Comment by laschultz** [comment]
ThunderFrame, thanks for pointing this out. It is likely an isolated error and has been fixed in this topic.
