### ISSUE TITLE
Maybe add a page for Font.Color Property (Word)

### ISSUE THREAD

**Issue by italicize** [OfficeDev/VBA-content#222]
Maybe add a page for **Font.Color Property \(Word\)**, like the page **[\_Font.Color property](https://msdn.microsoft.com/en-us/library/office/microsoft.office.interop.word._font.color.aspx)**.

The Color property is available but doesn't appear on the page **[Font Properties \(Word\)](https://msdn.microsoft.com/en-us/library/office/dn320660.aspx)**, only on the page **[Font properties](https://msdn.microsoft.com/en-us/library/office/microsoft.office.interop.word.font_properties.aspx)**.

(Or, if the Color property is deprecated, then change its description on the page **[Font properties](https://msdn.microsoft.com/en-us/library/office/microsoft.office.interop.word.font_properties.aspx)**, like the description of the Animation property that is deprecated.)

**Comment by laschultz** [comment]
Thanks you for your contribution. Your efforts help improve the technical accuracy of our documentation.

**Comment by italicize** [comment]
@laschultz, It's low priority, but Color doesn't appear in the properties table at [Font Members \(Word\)](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/04a3c706-4062-09bc-70d9-cef3748a7d57.md) or as a Font object property in the [Table of contents](https://github.com/OfficeDev/VBA-content/tree/master/Word-VBA). In the MSDN, Color doesn't appear in [Font Members \(Word\)](https://msdn.microsoft.com/en-us/library/office/ff845004.aspx) or [Font Properties \(Word\)](https://msdn.microsoft.com/en-us/library/office/dn320660.aspx). 
 
[Color](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/45ead200-5444-4ba0-b688-69a8f93d8dd6.md) appears in the properties table at [Font Properties \(Word\)](https://github.com/OfficeDev/VBA-content/blob/master/Word-VBA/articles/bd983744-50f2-4d53-95ab-c2d529dd7bb6.md), but the link didn't work. 
  
(I hope I don't become known as the person who reports the small problems.)

**Comment by italicize** [comment]
@laschultz Pages about Font.Color Property (Word) are not showing. Maybe reopen the issue. 
 
![font color property word screen capture](https://cloud.githubusercontent.com/assets/19557158/17868622/728835fc-6864-11e6-859b-cc3ac78a3163.PNG)
