### ISSUE TITLE
Navigation Button Shape properties not correct

### ISSUE THREAD

**Issue by GoeschWho** [OfficeDev/VBA-content#229]
VBA-content/Access-VBA/articles/9d9ecd73-b1a4-6861-a420-3bc52beae95c.md

https://msdn.microsoft.com/en-us/library/office/ff198250.aspx

The allowed NagivationButton.Shape value in reality (Office 2016 up to date as of June 2016) only go from 0 (defualt) to 7 (oval) NOT up to 9 as the page lists.  These values are valid for Command Buttons, but are not correct for Navigation buttons.

**Comment by laschultz** [comment]
Hi Goesch. This issue has been fixed in VSO task 817278. Thank you for your contribution, as it helps improve the overall quality of our VBA content. 
Office Scale Team
