### ISSUE TITLE
Word-VBA Field.Update documentation: return value inconsistent

### ISSUE THREAD

**Issue by cxw42** [OfficeDev/VBA-content#231]
[The Field.Update document](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/articles/e4e941aa-3223-ae0b-8366-9e14d92fff52.md) says that the return value is True on success, and later says the return value is 0 on success.  CLng(False)=0, so it can't be both :) .  On my Word 2013 install, the Object Browser shows Field.Update as returning Boolean, True appears to be the return value for success, and False appears to be the return value for failure.  Would you please confirm and correct the document?  Thank you!

**Comment by laschultz** [comment]
cxw42, Thank you for pointing this out. It should be 1 for TRUE, so I've fixed the documentation to reflect this change. Your contribution helps ensure the technical accuracy of the VBA documentation. 
Office Scale Team
