### ISSUE TITLE
Cant access address book through Outlook VB using example in the docs

### ISSUE THREAD

**Issue by STashakkori** [OfficeDev/VBA-content#234]
The example in the docs gives compilation errors. At this point all I have left to do is trial and error. Please assist. All I want to do is populate a ComboBox with the names in the address book. Either that or use the addressbook popup to select a name that will then show up in the field. Whatever is easier.

**Comment by laschultz** [comment]
STashakkori, thank you for bringing this issue to our attention. Could you please include the URL to the documentation topic that you are referring to? thanks
Office Scale TEam

**Comment by STashakkori** [comment]
Hi Laura,

Thank you for the quick response.

Pretty much everything on this website:
https://msdn.microsoft.com/en-us/library/office/ff863719.aspx

I can't Dim <variable_name> As <type> in my outlook 2013. So for example if
I say Dim num As Integer I get a compilation error.

I need a way to bring up the address book with a button the populate a
field that is not a "To.." field, it simply holds the name variable.

I also need a way to send an email programmatically.

These actions both require references of some sort in Visual Basic to the
Office infrastructure.

Here's the idea:

I want to have a user form that has a number of fields and a send button.
When the send button is clicked, I want to generate an email with form
fields embedded in it and send it.

I am well versed in VBA from a former job with a Microsoft Partner,
however, I right now can't do simple tasks based on the documentation.

My work around for this was to use C# in Visual Studio to create a Windows
Form that I could build into a .exe however I had another issue there: I
could not grab the Microsoft.Office.Core reference through the wizard.

I am starting to wonder if maybe my Office 365 ProPlus suite is the reason
why I can't do some of these things. That or I might just be too dumb.

If you have anyone on hand that can help me achieve the task that I
mentioned earlier or at least help me get up and running I would be
extremely grateful.

Best,
Sina

**Comment by laschultz** [comment]
STashakkori, 
Thanks for your email. The VBA docs is legacy content and was discontinued with the Office 365 suite. You can go to one of these forums for support, as this listserve is strictly to for updating content specific to legacy documentation. We are not able to help you with troubleshooting on this site. Thank you.
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=outlookdev
http://stackoverflow.com/questions/tagged/outlook
Office Scale Team
