### ISSUE TITLE
Links after 'The VBA references available include' in README are broken.

### ISSUE THREAD

**Issue by stevemoser** [OfficeDev/VBA-content#236]
Links go to Github 404.

**Comment by Lauragra** [comment]
Hi stevemoser, thanks for pointing that out. The VBA references are available in this location: https://github.com/OfficeDev/VBA-content/tree/master/VBA/Offline-Docs. We'll get the links fixed asap.

**Comment by laschultz** [comment]
stevemoser,
Thank you for bringing this to our attention. Your contribution helps make our documentation more technically accurate. 
Office Scale Team
