### ISSUE TITLE
Unicode Support?

### ISSUE THREAD

**Issue by XeroByt3** [OfficeDev/VBA-content#238]
Regarding [ClipBoard_SetData](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/4261f071-7bff-b290-c3d3-03645fd9ada0.md):
I'm a noob, so I could be missing something simple, but it seems to me that using the windows API to put a string containing Unicode characters doesn't work as expected. It replaces all the characters with question marks (?).

I've got VBA code (used in Excel) that takes the contents of a cell and puts the text value in the clipboard. 
For example: lets say A1 contains `=UNICHAR(1234)`
The code would be:
`x = ClipBoard_SetData(Range("A1").Value) `
and the result would be that the clipboard contains a question mark (?)

Any ideas how to modify the code to get Unicode characters working?

I've tried changing the value of CF_TEXT from 1 to 13 as per [this link](https://msdn.microsoft.com/en-us/library/windows/desktop/ff729168(v=vs.85).aspx), however this instead put a series of strange characters into the clipboard, even with a normal non-Unicode string.

**Comment by XeroByt3** [comment]
I'd just like to update this:
I found a solution that worked for me pulled and slightly modified from an answer [here](http://stackoverflow.com/questions/540361/whats-the-best-option-to-display-unicode-text-hebrew-etc-in-vb6).

```
Option Explicit
Private Declare Function OpenClipboard Lib "user32.dll" (ByVal hWnd As Long) As Long
Private Declare Function EmptyClipboard Lib "user32.dll" () As Long
Private Declare Function CloseClipboard Lib "user32.dll" () As Long
Private Declare Function IsClipboardFormatAvailable Lib "user32.dll" (ByVal wFormat As Long) As Long
Private Declare Function GetClipboardData Lib "user32.dll" (ByVal wFormat As Long) As Long
Private Declare Function SetClipboardData Lib "user32.dll" (ByVal wFormat As Long, ByVal hMem As Long) As Long
Private Declare Function GlobalAlloc Lib "kernel32.dll" (ByVal wFlags As Long, ByVal dwBytes As Long) As Long
Private Declare Function GlobalLock Lib "kernel32.dll" (ByVal hMem As Long) As Long
Private Declare Function GlobalUnlock Lib "kernel32.dll" (ByVal hMem As Long) As Long
Private Declare Function GlobalSize Lib "kernel32" (ByVal hMem As Long) As Long
Private Declare Function lstrcpy Lib "kernel32.dll" Alias "lstrcpyW" (ByVal lpString1 As Long, ByVal lpString2 As Long) As Long

Public Sub SetClipboard(sUniText As String)
    Dim iStrPtr As Long
    Dim iLen As Long
    Dim iLock As Long
    Const GMEM_MOVEABLE As Long = &H2
    Const GMEM_ZEROINIT As Long = &H40
    Const CF_UNICODETEXT As Long = &HD
    OpenClipboard 0&
    EmptyClipboard
    iLen = LenB(sUniText) + 2&
    iStrPtr = GlobalAlloc(GMEM_MOVEABLE Or GMEM_ZEROINIT, iLen)
    iLock = GlobalLock(iStrPtr)
    lstrcpy iLock, StrPtr(sUniText)
    GlobalUnlock iStrPtr
    SetClipboardData CF_UNICODETEXT, iStrPtr
    CloseClipboard
End Sub

Public Function GetClipboard() As String
    Dim iStrPtr As Long
    Dim iLen As Long
    Dim iLock As Long
    Dim sUniText As String
    Const CF_UNICODETEXT As Long = 13&
    OpenClipboard 0&
    If IsClipboardFormatAvailable(CF_UNICODETEXT) Then
        iStrPtr = GetClipboardData(CF_UNICODETEXT)
        If iStrPtr Then
            iLock = GlobalLock(iStrPtr)
            iLen = GlobalSize(iStrPtr)
            sUniText = String$(iLen \ 2& - 1&, vbNullChar)
            lstrcpy StrPtr(sUniText), iLock
            GlobalUnlock iStrPtr
        End If
        GetClipboard = sUniText
    End If
    CloseClipboard
End Function
```

**Comment by laschultz** [comment]
XeroByt3, 
Thanks so much for your contribution. Your efforts help improve the quality of our VBA documentation. For this code example, I'm curious which version of Windows are you using?
Thanks, 
Office Scale Team
