### ISSUE TITLE
Inconsistent Labeling

### ISSUE THREAD

**Issue by secowden** [OfficeDev/VBA-content#239]
Is labeled "PivotTable.Slicers Property" but is described (properly) as a Collection. This inconsistency in labeling occurs throughout the PivotTable object documentation. It is very misleading and could cause unnecessary confusion to some. As for me, I just learn to not trust the documentation - kind of antithetical to the purpose of documentation. :)

**Comment by laschultz** [comment]
Secowden,
Can you please describe how this causes unnecessary confusion. The PivotTable Members topic https://github.com/OfficeDev/VBA-content/blob/d92af56f76b229dbd21f71c7ea698e068e100dce/VBA/Excel-VBA/articles/8e8d1692-cf32-63c6-a1f6-54ddcc2a4964.md includes tables that list all of the methods and properties for the PivotTable object.  The "property" returns a Slicers collection.  The Slicers collection includes "slicer" objects. I hope this clears up your confusion. 
Thanks,
Office Scale Team
