### ISSUE TITLE
Missing reference for parameter CodePage

### ISSUE THREAD

**Issue by GustavBrock** [OfficeDev/VBA-content#244]
For [DoCmd.TransferText](https://msdn.microsoft.com/en-us/library/office/ff835958(v=office.15).aspx#Anchor_0), a link should be provided to the reference for the possible values of the last parameter: CodePage

That reference is found at a different site, the Windows documentation: [Code Page Identifiers](https://msdn.microsoft.com/en-us/library/windows/desktop/dd317756(v=vs.85).aspx)

Further, the example code ignores this important parameter completely.

**Comment by laschultz** [comment]
GustavBrock,
Thanks for your contribution. I've created a link to the page from the CodePage parameter to the Windows documentation. If you'd like to make a suggestion to our code example, feel free to make the suggestion directly on our GitHub open publishing repo at https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/e59f26dc-2df8-8d87-b73d-f3004eed0719.md.
Office Scale Team

**Comment by GustavBrock** [comment]
Thanks Laura - I can see the change at GitHub. 
But - just curious - when will it "go live"? I'm new to this, so I'm not familiar with the intervals or schedules for rebuilding the documentation.
