### ISSUE TITLE
Document how to call shared libraries on Excel 2016 from add-in

### ISSUE THREAD

**Issue by ibell** [OfficeDev/VBA-content#248]
I gather that sandboxing has been added to Excel 2016 add-ins on OSX.  This breaks add-ins that have in their header something like:
```
Option Explicit
#If Mac Then
Private Declare Function PropsSI_private Lib "libCoolProp.dylib" Alias "PropsSI" (ByVal Output As String, ByVal Name1 As String, ByVal Value1 As Double, ByVal Name2 As String, ByVal Value2 As Double, ByVal Ref As String) As Double
Private Declare Function PhaseSI_private Lib "libCoolProp.dylib" Alias "PhaseSI" (ByVal Name1 As String, ByVal Value1 As Double, ByVal Name2 As String, ByVal Value2 As Double, ByVal Ref As String, ByVal Output As String, ByVal n As Integer) As Long
...
```
because at add-in load time, we can't call any functions before the shared library is tried to be loaded.

Previously we just needed to make sure that the correct shared library was in ~/lib, but that no longer works.  How do we modify our add-in to defeat the sandboxing and allow us to call the shared library?

If I have asked this question in the wrong place, please direct me to the appropriate location.

**Comment by laschultz** [comment]
ibell,
Thanks for your question. Yes, sandboxing has been added and I'm working on adding the following note to MSDN. "The Sandbox Solution framework provides a mechanism for executing user-provided code outside of the IIS worker process. The Sandbox Solution framework should not be used as a mechanism for enforcing security boundaries when executing user code. Sandbox Solutions are not supported as a security boundary with user code, especially code of unknown origin. We advise against executing Sandbox Solutions of unknown origins." 
This GitHub site is for suggesting changes and additions to the Office VBA documentation. For more help with your code, I suggest that you post your question on one of these forums: 
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=excel 
http://stackoverflow.com/questions/tagged/excel

**Comment by laschultz** [comment]
ibell,
Thanks for your question. This GitHub site is for suggesting changes and additions to the Office VBA documentation. For more help with your code, I suggest that you post your question on one of these forums: 
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=excel 
http://stackoverflow.com/questions/tagged/excel
