### ISSUE TITLE
Two "Glossary" pages

### ISSUE THREAD

**Issue by Daniel15** [OfficeDev/VBA-content#251]
There's two glossary pages:

 - [Glossary (Microsoft Forms)](https://msdn.microsoft.com/en-us/library/office/jj692800.aspx) - [6c8b42d0-e2f1-4582-af57-323df0b79195.md](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/6c8b42d0-e2f1-4582-af57-323df0b79195.md)
 - [Glossary (VBA)](https://msdn.microsoft.com/en-us/library/office/gg278534.aspx) - [7ce2c60f-29fb-96e2-2516-73c99a6e7cff.md](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/7ce2c60f-29fb-96e2-2516-73c99a6e7cff.md)

The first page just consists of a link to the second page. This seems a bit silly, and I think the first one should instead just redirect to the second one.

**Comment by laschultz** [comment]
Daniel15. Thanks for bring this to our attention. The first page has been removed and the change should appear on the Dev Network site within 24 hours.
