### ISSUE TITLE
Several files have merge conflict markers in them

### ISSUE THREAD

**Issue by Daniel15** [OfficeDev/VBA-content#252]
Some examples:
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/readme.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/readme.md

I'd suggest auditing all files by searching for "<<<<<<< HEAD".

cc @laschultz

**Comment by laschultz** [comment]
Daniel15, Thanks for your contribution. I removed this from the readme files, and will investigate how these markers were generated in the first place.
Office Scale Team
