### ISSUE TITLE
Length of Bookmark.Name in Word

### ISSUE THREAD

**Issue by nonfree** [OfficeDev/VBA-content#253]
Please document that in Microsoft Word the `Name` argument for `Bookmarks.Add()`[*](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/articles/647795da-d7e2-7b6f-c412-5b684ec962a2.md) should not exceed 40 characters, as `Bookmark.Name`[*](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/articles/be6b0c7b-60ca-97e7-ef19-6de335da3197.md) is limited to this length, therefore the `Name` argument for `Bookmarks.Exists()`[*](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/articles/7a9df80d-1a52-022f-f234-336369b73fca.md) should not exceed 40 characters accordingly or might otherwise lead to unexpected results.

**Comment by laschultz** [comment]
Fixed this in Word topics Bookmarks.Exists and Bookmarks.Add. In the future, feel free to make the changes directly in GitHub and submit a Pull Request. We appreciate your contribution to making the VBA documentation better.
Office Scale Team

**Comment by nonfree** [comment]
Thank you very much. After I had to waste many hours to investigate this undocumented limitation as the cause for a bug in our application, I did not want to waste even more time with contributing to a repository that is restrictively licensed. The hope is that this issue and your fix will save other developers their time. So again, thank you very much.
