### ISSUE TITLE
QueryTable.Refresh has a huge memory leak on Mac

### ISSUE THREAD

**Issue by BrazilianJoe** [OfficeDev/VBA-content#254]
Currently on Excel 64-bits for Mac this function call causes excel to become unresponsive and starts eating memory nonstop, allocating 60GB in around a minute.

**Comment by laschultz** [comment]
Joe,
Thanks for leaving us this message. This GitHub repo is for developers to recommend updates to the  Office VBA documentation. For issues with your code, we suggest that you post your question on one of these forums:  
Example (Office) 
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=officedev 
http://stackoverflow.com/questions/tagged/vba
Thanks, 
Office Scale Team
