### ISSUE TITLE
Index is missing

### ISSUE THREAD

**Issue by klonuo** [OfficeDev/VBA-content#257]
Hi,

just to note, that generated chm files, miss indexes. Hopefully indexes exist.

**Comment by laschultz** [comment]
Klonuo,
Thank you for your inquiry. We will look into this issue and get back to you shortly.
Office Scale Team

**Comment by laschultz** [comment]
Klonuo,
Thank you for your feedback. Please note that we provide the CHM files as a snapshot of the documentation. We don’t plan to maintain or update them moving forward. For the latest content, please view the files in GitHub or on MSDN.
Office Scale Team
