### ISSUE TITLE
Update flags for Mac 64-bit builds

### ISSUE THREAD

**Issue by ibell** [OfficeDev/VBA-content#259]
I just got the 64-bit version of Excel, but I can't figure out what compilation constants I should use to differentiate between 32-bit and 64-bit Excel on OSX, please update the docs.  According to the docs for Office 2013, the only Mac-related flag is ``Mac``, which doesn't allow for conditional compilation to differentiate between 32-bit and 64-bit Excel.

**Comment by laschultz** [comment]
ibell, 
I'm the technical writer assigned to address the documentation issue that you've discovered. Can you please provide more specifics regarding the docs for Office 2013. Are there URLs you can include that specifically need addressing? 
Thanks, 
Office Scale Team

**Comment by laschultz** [comment]
Hi again ibell, 
Is this the topic you're saying needs to be updated? https://github.com/OfficeDev/VBA-content/blob/master/VBA/Office-Mac-VBA/MacOfficeVersion.md
thanks

**Comment by ibell** [comment]
Aha, yes, you should update this other page to link it to that one: https://msdn.microsoft.com/en-us/library/office/gg264614.aspx
