### ISSUE TITLE
International issue

### ISSUE THREAD

**Issue by jkpieterse** [OfficeDev/VBA-content#261]
When pasting an object from e.g. Word one of the format options is "Picture (Enhanced metafile)".
Unfortunately, this text is locale dependent. So if I have a Dutch installation of Office, the option must read "Afbeelding (enhanced metabestand)". Trying to use the US text causes a runtime error.
I think this information should be included in the documentation (and a workaround would be nice!)

**Comment by laschultz** [comment]
jkpierterse,
Thank you for bringing this issue to our attention. Currently we localize the VBA reference on MSDN. It will be available on GitHub in the near future. Your contribution helps improve the quality of our documentation.  
https://msdn.microsoft.com/de-de/library/office/gg264383(v=office.15).aspx
Office Scale Team

**Comment by jkpieterse** [comment]
Hi Laura,
Please make sure this information is included with the English documentation as well. Add-ins using this technique will only work on English Excel and add-ins are often used by people from around the world.
