### ISSUE TITLE
 attachment.PropertyAccessor.GetProperty( PR_ATTACH_DATA_BIN) fails if mailitem not saved

### ISSUE THREAD

**Issue by blesliecan** [OfficeDev/VBA-content#264]
Before you can access the attachment data the mail item must be saved.

At least that is what I had to do using outlook 2016 in order to get this example to work.
https://msdn.microsoft.com/en-us/library/office/hh290849.aspx

I had to add:
mailItem.save();

**Comment by laschultz** [comment]
blesliecan,
Thank you for your contribution. I added a note to the topic specifying the need to save the mail item. In the future, feel free to make changes directly to the topic in your branch, and submit a pull request. Your contribution helps make our documentation more accurate.
Office Scale Team
