### ISSUE TITLE
Code throws an error

### ISSUE THREAD

**Issue by Hoozits728** [OfficeDev/VBA-content#269]
This code

With Worksheets(1).Range("a1:a500") 
    Set c = .Find(2, lookin:=xlValues) 
    If Not c Is Nothing Then 
        firstAddress = c.Address 
        Do 
            c.Value = 5 
            Set c = .FindNext(c) 
        Loop While Not c Is Nothing And c.Address <> firstAddress 
    End If 
End With

thows an error because if c is Nothing (i.e., no more finds) after .FindNext, then a

VBA: error 91 Object variable or with block variable not set

error is thrown.

Consider handling like so instead

With Worksheets(1).Range("a1:a500") 
    Set c = .Find(2, lookin:=xlValues) 
    If Not c Is Nothing Then 
        firstAddress = c.Address 
        Do 
            c.Value = 5 
            Set c = .FindNext(c) 
            If c is Nothing Then
                GoTo DoneFinding
            End If
        Loop While c.Address <> firstAddress 
    End If 
DoneFinding:
End With

Although many discourage the use of the GoTo, this slightly modified version of otherwise helpful code accomplishes its intended task without throwing an error in the situation I mentioned. Perhaps an Exit Do in place of the GoTo construct would be better.

**Comment by laschultz** [comment]
Hoozits728,
Thanks for your contribution. I've made the change to the code at the following location. In the future, feel free to make the change and create a Pull Request. Your contribution improves the accuracy of our documentation.
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/308c6241-2398-13e6-ba68-17ec713376f6.md
Office Scale Team

**Comment by Hoozits728** [comment]
My pleasure.

I noticed that the change does not show up here
<https://msdn.microsoft.com/en-us/library/office/ff839746.aspx>, however.

Matt

**Comment by laschultz** [comment]
Matt,
It takes a few hours for the change to render on MSDN. If you check back tomorrow morning the change should be reflected. 
Laura

**Comment by Hoozits728** [comment]
OK. Thank you. I appreciate it a great deal.

Matt
