### ISSUE TITLE
Code example fails for `Masters.AddEx` Method 

### ISSUE THREAD

**Issue by nashwaan** [OfficeDev/VBA-content#271]
This code example in `Masters.AddEx Method` [documentation](https://msdn.microsoft.com/en-us/library/office/ff767654.aspx) fails. Not sure if the [code example](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Visio-VBA/articles/a27b1a7c-37f4-90c9-91f1-2249611a3cf9.md#example) is incorrect or something wrong with Visio configuration.

I created a new Visio document and then ran the example code against the new document.

```vb
Public Sub AddEx_Example()
    Dim vsoMaster As Visio.Master
    Set vsoMaster = Visio.ActiveDocument.Masters.AddEx(visTypeDataGraphic)
    Debug.Print vsoMaster.Name
End Sub
```

I am using Visio 2013. I tried this on two machines and both fails.

**Comment by laschultz** [comment]
Nashwaan,
Thank you for sending this information. This feedback service is for suggesting changes and additions to the Office VBA documentation, not a forum for developer support. For issues with addressing your code, we suggest that you post your question on one of these support forums:  
https://social.msdn.microsoft.com/Forums/office/en-US/home?sort=relevancedesc&brandIgnore=True&searchTerm=visio
http://stackoverflow.com/questions/tagged/visio
