### ISSUE TITLE
Example does not work

### ISSUE THREAD

**Issue by johnyradio** [OfficeDev/VBA-content#276]
On Excel Mac 2016, on Macbook Pro/Sierra:
Microsoft example from https://msdn.microsoft.com/en-us/library/office/gg264812.aspx 

Running this macro, the MacScript line raises:

> Runtime error '5'. Invalid procedure call or argument.

```
Sub Test()
    ThePath$ = MacScript("ChooseFile")
End Sub
```

**Comment by johnyradio** [comment]
according to this post, MacScript is not longer supported. 
That means Microsoft documentation linked above is wrong.

http://stackoverflow.com/a/30949324/209942

**Comment by laschultz** [comment]
johnyradio,
Thanks for your contribution to the VBA Object Model reference. Your suggested change helps us improve the quality our documentation. I've made the change to the article at https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/d845de85-a0d8-e10e-1174-8571e42bb8d2.md. The update will also be made in MSDN in the next 24 hours.
Office Scale Team
