### ISSUE TITLE
ActiveWorkbook.SaveCopyAs does not save using URL to a SharePoint site

### ISSUE THREAD

**Issue by Roosta1** [OfficeDev/VBA-content#277]
Get an error trying to save a worksheet over a network connection (SharePoint) using the  ActiveWorkbook.SaveCopyAs method.

The ActiveWorkbook.SaveAs method works fine, however.

**Comment by laschultz** [comment]
Roosta1, 
Thank you for sending this information. This feedback service is for suggesting changes and additions to the Office VBA documentation, not a forum for getting developer support. If you'd like to suggest a change to our documentation, you can go directly to a GitHub topic, make the change, and then submit a PR request. 
Office Scale Team
