### ISSUE TITLE
SetLastPriority Method (Remarks Proposed Change)

### ISSUE THREAD

**Issue by BenGrimm78** [OfficeDev/VBA-content#279]
Under "Remarks," it says, "this method will cause the priority of rules that had a priority value greater than this rule to be increased by one."  But, if this method "sets the evaluation order for this conditional formatting rule so it is evaluated after all other rules on the worksheet," wouldn't the effect of this method on any other rules with a priority value greater than this one to be decreased by one?  Say there are 5 rules on the worksheet and originally, "x" happens to have a priority level of 3 -> 1, 2, x, 4, 5.  A programmer chooses later to use the SetLastPriority method on "x," so wouldn't we decrement 4 and 5 by one and thus have -> 1, 2, 3, 4, x and not -> 1, 2, x, 5, 6?

**Comment by laschultz** [comment]
BenGrimm78,
Thank you for the information, which has been determined to warrant an update to 7 Excel topics that discuss the SetLastPriority method. Your contribution helps improve the quality of our documentation. 
Office Scale Teams.
