### ISSUE TITLE
Content control ID change?

### ISSUE THREAD

**Issue by cyclingzealot** [OfficeDev/VBA-content#280]
Reading about control control (https://github.com/OfficeDev/VBA-content/blob/master/VBA/Word-VBA/articles/b4092c71-a383-f1db-8d68-de69e8d8a86b.md), we were just wondering if the content control IDs of unchanged items change if we add or delete other items in a word document.

**Comment by laschultz** [comment]
cyclingzealot,
Thank you for sending this information. This feedback service is for suggesting changes and additions to the Office VBA documentation, not a forum for getting developer support. I suggest you post your question to one of our support forums:
https://social.msdn.microsoft.com/Forums/office/en-US/home?forum=worddev 
http://stackoverflow.com/questions/tagged/word
Office Scale Team
