### ISSUE TITLE
Variable Type for constants pjTaskItem, pjResourceItem, and pjOtherItem not specified

### ISSUE THREAD

**Issue by simplethingsformsp** [OfficeDev/VBA-content#286]
I went to the VBA help for Project to find the variable type for the MS Project TaskTable.TableType constants, pjTaskItem, pjResourceItem, and pjOtherItem, but if it's there, I'm not finding it.  Wanted to know if the values are Long, Integer, etc.  Isn't this kind of information usually included?  Yes, I can use the VarType function to find out, but don't remember what kind of variable a VarType value of "3" is without looking it up as well.

**Comment by AJMayMSFT** [comment]
From what I see, it's a PjItemType enumeration, as specified in this reference topic: https://msdn.microsoft.com/en-us/library/ff863263.aspx. Does that give you the info you need?
