### ISSUE TITLE
MS ACCESS average function

### ISSUE THREAD

**Issue by mhackeras** [OfficeDev/VBA-content#300]
when using avg function in greek it doesn't use avg and uses Μεσος_ορος and returns a message saying that this function doesn't exist. I get this bug in Max and some other functions too

**Comment by lindalu-MSFT** [comment]
@mhackeras I apologize for the delay in answering your issue. This repo was orphaned for some time and I only recently adopted it and have been trying to get to the bottom of all the issues. Are you still experience the problem using the avg function in Greek? If so, can you please open a new issue and point to the documentation page so we can provide clarity? THANKS, lindalu
