### ISSUE TITLE
readability statistic moved in Word 2016

### ISSUE THREAD

**Issue by TaskForce1** [OfficeDev/VBA-content#306]
"The statistics are ordered as follows: Words, Characters, Paragraphs, Sentences, Sentences per Paragraph, Words per Sentence, Characters per Word, Passive Sentences, Flesch Reading Ease, and Flesch-Kincaid Grade Level. "
This statement no longer seems to be valid in Word 2016. "Passive Sentences" was moved to the end of the list.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
