### ISSUE TITLE
Document strategies for embedding double-quotes (") inside a string literal

### ISSUE THREAD

**Issue by zspitz** [OfficeDev/VBA-content#327]
There are two options:

    Dim s As String
    s = "This string has an embedded """ in it."
    s = "This string has an embedded " & Chr(34) & " in it."

**Comment by JohnAustin-MSFT** [comment]
Good idea. You are welcome to fork this repository, create a branch off of master, make the addition to the appropriate topic, and create a pull request. We will be very happy to review it and merge if it is acceptable.
