### ISSUE TITLE
Contradictory licensing info

### ISSUE THREAD

**Issue by iainnicol** [OfficeDev/VBA-content#335]
The file LICENSE.md says this documentation is CC-NC-ND.  That file was added a year ago.

In contrast the file LICENSE (no extension), plus LICENSE-CODE and ThirdPartyNotices, says the license is CC-BY, with MIT for code.  These files were added only a month ago.

Assuming the newer, more permissive, license is intenional, can the old license file (LICENSE.md) be deleted?

**Comment by JohnAustin-MSFT** [comment]
Great question!  I'll get to the bottom of it tomorrow and correct the issue.
