### ISSUE TITLE
Document the variant parameter types

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/VBA-content#340]
Many methods in MS Office COM API define parameter types as `VT_VARIANT` (**Variant**).
This is set in the **Data Type** column in the documentation. As a developer I must read the **Description** to know what is the data type of an actual parameter.

Can you create a new column, **Expected Data Type** which will containt an actual type name (bool, string, enum name, etc.) so the documentation provides more structured description of method parameter types?

I understand not all parameters have data type documented in the Description - you can leave the column empty, or include the **Variant** again. But even having just a few more parameters documented in more structured way will help.

PS: This will greatly help in development of the NetOffice library, which provides .NET wrapper for MS Office applications COM API. Many wrapper methods contain parameters with `object` type, which is not very helpful. If we can gather these expected data types we can create better wrapper methods.

**Comment by JohnAustin-MSFT** [comment]
Hi Joze,
That's a good observation!  I like the idea and will look at the feasibility of the fix. It isn't a quick fix because of the sheer size of the SDK with tens of thousands of reference topics. However, this is something that may be automated.  Stand by for further news :-)
John
