### ISSUE TITLE
Drag down formulas in single VBA code for Different range at same location

### ISSUE THREAD

**Issue by Ghanshyamsavaliya** [OfficeDev/VBA-content#344]
Hello Sir,

I want to Drag down formulas in single VBA code for the Different range at the same location in Excel Sheet. Could you please help me on this?

Thanks.

**Comment by JohnAustin-MSFT** [comment]
Questions about how VBA code works in your add-in should be asked in [StackOverflow](https://stackoverflow.com/questions/tagged/vba)
