### ISSUE TITLE
Document new PowerPoint VBA Properties

### ISSUE THREAD

**Issue by keyur32** [OfficeDev/VBA-content#348]
The following properties for PowerPoint need documentation:

Axis.CategorySortOrder Property (PowerPoint)
XlValueSortOrder Enumeration (PowerPoint)
Series.ValueSortOrder Property (PowerPoint)
Presentation.WorkIdentity Property (PowerPoint)
Shape.HasSectionZoom Property (PowerPoint)
XlCategorySortOrder Enumeration (PowerPoint)
ShapeRange.HasSectionZoom Property (PowerPoint)

**Comment by lindalu-MSFT** [comment]
@keyur32 John left me a VBA template, is there a place that I can grab the syntax for these items?

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
