### ISSUE TITLE
application.screenupdating = false not working(Office 365 Mac) 

### ISSUE THREAD

**Issue by zechn** [OfficeDev/VBA-content#381]
Unfortunately application.screenupdating = false is not working with Office 365 for Mac.
Only the data in the grids are not shown, everything else is updated so it doesn't increase the speed of my macros any more. When merging 1.000 different Workbooks to a single Worksheets this brings me in real troubles!

**Comment by lindalu-MSFT** [comment]
@zechn  Hi, this is a bug in the product, not the documentation correct? Sorry this reply is so late. I inherited this repo only recently and am slogging through the backlog. Let me know if there's a topic you suggest I update. Please open an new issue and tag me! Thanks, lindalu@microsoft.com
