### ISSUE TITLE
Excel's Application.Selection -- what does it return?

### ISSUE THREAD

**Issue by zspitz** [OfficeDev/VBA-content#382]
From the [documentation for `Excel.Application`'s `Selection` property](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/application-selection-property-excel.md):

> The returned object type depends on the current selection (for example, if a cell is selected, this property returns a  **[Range](range-object-excel.md)** object). The **Selection** property returns **Nothing** if nothing is selected.

It would be helpful to know what specific kinds of objects this can return.

**Comment by shengbrad** [comment]
my understanding: 
Selection means the object(s) you selected.
in Excel you can select range, charts, shapes or controls etc... since this is the object, so the return depend on what you have selected.
the selection returns the object you have selected.
Depend on what is been selected. it has different class and property.

**Comment by zspitz** [comment]
@shengbrad Can you select a scrollbar? a window? a ribbon menu? There is a set of items which can be selected and other items which cannot. The `Selection` property thus can return only a specific set of types. It would be helpful to document precisely what possible type the object returned from `Selection` might be.

**Comment by andreismolingmail** [comment]
My understanding is that this property can only return objects that provide the Select() method.

**Comment by lindalu-MSFT** [comment]
Hi all @shengbrad @zspitz @andreismolingmail I updated the documentation and added info on TypeName. Thanks for the suggestion! [Application.Selection Property (Excel)](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/application-selection-property-excel.md).

[TypeName](https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/typename-function)
