### ISSUE TITLE
IBlogExtensibility.PublishPost parameters

### ISSUE THREAD

**Issue by jozefizso** [OfficeDev/VBA-content#394]
I see the `IBlogExtensibility.PublishPost()` method has documented these two parameters: **username** and **Password**.

Those parameters are not available in latest Microsoft Office 365 release (1708, Build 8431.2079).

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
