### ISSUE TITLE
Range.Sort Method (Excel): XlSortOrientation description wrong? 

### ISSUE THREAD

**Issue by bronx72** [OfficeDev/VBA-content#396]
Parameter Orientation (XlSortOrientation)	
Description given: "Specifies if the sort should be in acending or decending order."
Description suggested: "Specifies if the sort should be by row (default) or by column." 
To be even more helpful, you could add: "For top to bottom orientation, sort by column."

**Comment by lindalu-MSFT** [comment]
Fixed!
