### ISSUE TITLE
Extra ' ? ' in Example section - BUG 1597566

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#411]
**Repro steps**:
1) Go to https://msdn.microsoft.com/en-us/VBA/Access-VBA/articles/docmd-openform-method-access#example
2) See the header "Sample code provided by: ..." 

**GH Topic**:
https://github.com/OfficeGSX/VBA-content/blob/live/VBA/Access-VBA/articles/docmd-openform-method-access.md
**Fix**:
Change "?" for '

**Actual result**:
"?" character is in the header

**Expected result**:
"?" character should not be in the header

![header_repro](https://user-images.githubusercontent.com/16706698/31716226-2402ce16-b407-11e7-8565-a905f812359b.png)

**Comment by Linda-Editor** [comment]
I already fixed this in VSTS BUG 1552272 #415. No changes.
