### ISSUE TITLE
Unreadable string in Example section - VSTS BUG 1314967

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#412]
**Repro steps**:
1) Go to these two sites:
https://msdn.microsoft.com/en-us/library/d3bd2f3a-7fed-20fa-918d-a71e2a2a1d49(v=office.15,d=lightweight).aspx
https://msdn.microsoft.com/en-us/library/ede52b2f-9025-fc83-9c16-f09c6b89c5c2(v=office.15,d=lightweight).aspx
2) See the text "Holy Macro!..." in the example section

**GH Topic**:
https://github.com/OfficeGSX/VBA-content/blob/live/VBA/Excel-VBA/articles/application-inputbox-method-excel.md
**Fix**:
Change "?" for '

**Actual result**:
"?" should not present in the string
**Expected resul**:
"?" should not be present in the string

![holy_macro](https://user-images.githubusercontent.com/16706698/31719308-4668fde8-b413-11e7-89b8-2139ce809f9a.png)

**Comment by Linda-Editor** [comment]
I fixed these issues plus others I saw
