### ISSUE TITLE
The table under "Properties" section is not displayed correctly  - VSTS BUG 989169

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#413]
**Repro steps**:
1) Go to:
https://msdn.microsoft.com/en-us/library/179c32ce-49bd-6f36-ea12-89fb5443f3ea(v=office.15,d=lightweight).aspx
2) Navigate to "Properties" section see the table 
**GH Topic**:
https://github.com/OfficeGSX/VBA-content/blob/live/VBA/Excel-VBA/articles/chart-object-excel.md
**Fix**:
Remove the redundant part of the table and the "ShowDataLabelsOverMaximumShowExpandCollapseEntireFieldButtons" section should be separated into tho separate tabs.

![redundant_libes](https://user-images.githubusercontent.com/16706698/31720700-9110ecf8-b417-11e7-8f07-f0599356c6a8.png)

**Comment by Linda-Editor** [comment]
Fixed issues
