### ISSUE TITLE
Extra "*" characters under "Syntax" header - VSTS BUG 1877968

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#414]
**Repro steps**:
1) Go to 
https://msdn.microsoft.com/en-us/VBA/Access-VBA/articles/docmd-transferspreadsheet-method-access#parameters
2) See the Text under the "Syntax" header

**GH Topic**:
https://github.com/OfficeGSX/VBA-content/blob/live/VBA/Access-VBA/articles/docmd-transferspreadsheet-method-access.md
**Fix**:
Remove the space between the "**" character and the word
![additional_characters](https://user-images.githubusercontent.com/16706698/31721607-14800496-b41a-11e7-90a4-c65d29a57a55.png)

**Comment by Linda-Editor** [comment]
Fixed issues
