### ISSUE TITLE
"?" character instead of ' and "**" characters are shown under the "Syntax" header - VSTS BUG 1552272

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#415]
**Repro steps**:
1) Go to https://msdn.microsoft.com/en-us/library/office/a1c9d3a9-2af8-c30a-acb0-6428c70dcdb0(v=office.15,d=lightweight).aspx
2) See the text under the "Syntax" header
3) Navigate to the "Example" section and look at the "Sample code privded by:..." header 

**GH Topic**:
https://github.com/OfficeGSX/VBA-content/blob/live/VBA/Access-VBA/articles/docmd-openform-method-access.md
**Fix**:
1)Delete the space between "**" characters and the word
2) Put ' instead of the "?" character
![syntaxe_part1](https://user-images.githubusercontent.com/16706698/31721811-b1899b80-b41a-11e7-8a41-88190856043e.png)
![syntaxe_part2](https://user-images.githubusercontent.com/16706698/31721873-cdd1dcf8-b41a-11e7-8b1d-a3685e375d1b.png)

**Comment by Linda-Editor** [comment]
Fixed issues at https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-openform-method-access.md
--
