### ISSUE TITLE
comment position 

### ISSUE THREAD

**Issue by matthewbaynham** [OfficeDev/VBA-content#422]
When .shape.placement = xlmove then the comment follows the position of the row above and not it's own row.

This is a problem when you are auto filtering before you add the comment.  When you remove the auto filter you will see each comment has followed the wrong row.

**Comment by lindalu-MSFT** [comment]
@matthewbaynham Hi, sorry for the delay! If you are still having an issue, can you please open a new issue with the name of the file associated with the code? I don't know where to update or fix the documentation otherwise. Closing now, please open a new issue if you still have questions/need help.
