### ISSUE TITLE
Bold characters appearing next to text due to additional space

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#427]
**Repro steps:**
1. Go to https://msdn.microsoft.com/en-us/VBA/Access-VBA/articles/form-keypress-event-access
2. See the "** KeyAscii**" text under the "Syntax Header"

**Actual results:**
Text is shown as ** KeyAscii** instead of a bold text
**Expected results:**
Text should be shown as bold

**GH article:**
https://github.com/OfficeDev/VBA-content/blob/live/VBA/Access-VBA/articles/form-keypress-event-access.md
**Proposed fix:**
Remove the additional space at the beginning so that the text will apear bold.

![bold_text](https://user-images.githubusercontent.com/16706698/33171046-06ef47c2-d04b-11e7-86ce-abe09f48b361.png)

**Comment by Linda-Editor** [comment]
Fixed issue but am not seeing changes on stage or live yet.

**Comment by Linda-Editor** [comment]
The fix is now live: https://msdn.microsoft.com/en-us/VBA/Access-VBA/articles/form-keypress-event-access
