### ISSUE TITLE
Corrupted table

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#428]
**Repro steps:**
1. Go to https://msdn.microsoft.com/en-us/VBA/PowerPoint-VBA/articles/shapes-pastespecial-method-powerpoint
2. Navigate to the Return Value section 
3. See the broken table

**Actual result:**
Table is broken
**Expected result:**
Table should not be broken

**GH article:**
https://github.com/OfficeDev/VBA-content/blob/live/VBA/PowerPoint-VBA/articles/shapes-pastespecial-method-powerpoint.md
![broken_table](https://user-images.githubusercontent.com/16706698/33176164-62590a68-d05e-11e7-80a8-8fdf7aa28aaf.png)

**Comment by Linda-Editor** [comment]
Fixed. Changed table to a bulleted list, because the problem appeared to be that the table was only one column. Change is now live: https://msdn.microsoft.com/en-us/VBA/PowerPoint-VBA/articles/shapes-pastespecial-method-powerpoint
