### ISSUE TITLE
Multiple Topic - "?" character instead of " ' " character and the url ends with .mdl insteadh of .html

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#429]
**Repro steps:**
1. Go to https://msdn.microsoft.com/en-us/VBA/Access-VBA/articles/accessobject-isloaded-property-access
2. See the "Microsoft Access 2010 Programmer?s Reference" hyper link

**Actual result:**
The hyper link text contains "?" character instead of the ' character and the link forwards to .mdl file
**Expected result:**
The hyper link does not contains "?" and redirect to .html file
**Proposed fix:**
Change the "?" to ' and change the ".mdl" to ".html"

This is repro on multiple Articles See below:

**GH articles:**
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/accessobject-isloaded-property-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-transfertext-method-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/form-beforeupdate-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/report-nodata-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/report-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/report-open-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/report-recordsource-property-access.md

![hyper_link_text](https://user-images.githubusercontent.com/16706698/33436342-0a86a2fa-d5e5-11e7-940d-6c3e95b575ba.png)
![link](https://user-images.githubusercontent.com/16706698/33436346-0c26f34e-d5e5-11e7-8feb-975b36627764.png)

**Comment by Linda-Editor** [comment]
Fixed all issues and reviewed on stage. Also fixed other formatting issues on pages as needed.
