### ISSUE TITLE
Multiple links contain .mdl instead of .html - VSTS 1997575

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#434]
Multiple links  contains .mdl instead of .html resulting in 404 error message:
"Microsoft Access 2010 Programmer's Reference" 
"Display List of References - Both Good and Broken"
"here"
"Features and Limits of Using the SendObject Method to Send Emails"
"Email from Access"
"Microsoft Access Form Tips and Avoiding Common Mistakes"
"Microsoft Office Access 2007 Form Design Tips"
"Transfer data from Access to Excel"
"Create a Query that uses a Multi-select Listbox as Criteria"
"ListBox Picker"
"Populate a Listbox with Files from a Directory"
"VBOffice.net"
**Repro steps:**
1) Go to https://msdn.microsoft.com/en-us/vba/access-vba/articles/allforms-object-access
2) Click on the "Microsoft Access 2010 Programmer's Reference" link
**Actual result:**
Link redirect to 404
**Expected result:**
Link redirects to a valid page
**Proposed fix:**
remove the ".mdl" a replace it with the ".html"

This is repro on multiple articles see below:
**GH articles:**
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/allforms-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-notinlist-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/combobox-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/currentproject-istrusted-property-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-openform-method-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/form-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/form-openargs-property-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/report-page-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/section-paint-event-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/application-references-property-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/docmd-sendobject-method-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/form-recordsetclone-property-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/listbox-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Access-VBA/articles/references-object-access.md
https://github.com/OfficeDev/VBA-content/blob/master/VBA/Outlook-VBA/articles/mailitem-sender-property-outlook.md

**Comment by OfficeGSX** [comment]
Hello,

After this is done could you please merge this fix and the fix from the gh [issue](https://github.com/OfficeDev/VBA-content/issues/429) and merge the fixes to live branch.

Thank you,

Jiri

**Comment by Linda-Editor** [comment]
@davidchesnut  Hi David, I've pushed the changes for #435 and #429 to master; can you push these to live?
