### ISSUE TITLE
Language Reference VBA Missing Link to Type Conversion Functions

### ISSUE THREAD

**Issue by matthiasdenu** [OfficeDev/VBA-content#440]
It would by nice if the information at https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/type-conversion-functions were easier to find. I wasn't able to find a link to it from the Language Reference VBA page.

**Comment by lindalu-MSFT** [comment]
Hi @matthiasdenu - 

I verified this is in the TOC in the [VBA Language Reference](https://msdn.microsoft.com/en-us/vba/vba-language-reference): 
1. Expand the Language Reference TOC
2. Select [Functions](https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/functions-visual-basic-for-applications)
3. On the Functions landing page, scroll to [Type Conversions Functions](https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/type-conversion-functions)
The VBA ref is quite large and it isn't possible to include every topic in the TOC. So we use landing pages to aid in the navigation.
Closing this as "won't fix."
