### ISSUE TITLE
Shapes.AddTextbox ignores the anchor object

### ISSUE THREAD

**Issue by makzr** [OfficeDev/VBA-content#444]
It seems that you removed the optional anchor parameter from the methods Shapes.AddTextbox, .AddShape, .AddCanvas, ...

In Word 2010 you could add a range parameter to specify the range of the anchor. It no longer works in Word 2016. It seems that you removed it from the documentation as well.

Is there any alternative solution? The AddTextbox method would be quite useless if you could no longer specify the anchor.

I also found an "unanswered" question in the MSDN forums referring to this: https://social.msdn.microsoft.com/Forums/office/en-US/f175055e-7b40-4bcb-8409-d4e0910022f4/documentshapesaddtextbox-ignores-anchor-word-2013?forum=worddev

**Comment by lindalu-MSFT** [comment]
@makzr So sorry for the delayed answer. Have you tried the [Shape.Anchor property](https://msdn.microsoft.com/en-us/vba/word-vba/articles/shape-anchor-property-word)? I think that's what you're looking for. If not, please reopen and let me know. Thanks, linda
