### ISSUE TITLE
MeetingItem.BodyFormat property is missing

### ISSUE THREAD

**Issue by andreismolingmail** [OfficeDev/VBA-content#468]
In the VBA object browser in Outlook 2016 Insider I see this property non-hidden.

**Comment by lindalu-MSFT** [comment]
@andreismolingmail Can you please provide more info?

**Comment by andreismolingmail** [comment]
Hello Linda, 

 

Sorry for the misleading title. I was trying to inform you that the help
reference doesn’t describe the MeetingItem.BodyFormat property. That
property is available in Outlook 2016; below is a screenshot of the Object
Browser opened in my Outlook ProPlus. 

 



 

Regards from Belarus (GMT+3),

 

Andrei Smolin

Add-in Express Team Leader

**Comment by lindalu-MSFT** [comment]
@andreismolingmail Hi, I checked and this property doesn't exist. Sorry to disappoint you. However, here are a few topics that might help.
This topic is about formatting a mail item in Outlook VBA: [MailItem.BodyFormat](https://msdn.microsoft.com/en-us/vba/outlook-vba/articles/mailitem-bodyformat-property-outlook). You could also try StackOverflow for a solution. I've seen a couple examples of BodyFormat in HTML:
[StackOverflow search BodyFormat](https://stackoverflow.com/search?q=bodyformat).
