### ISSUE TITLE
Link "CurDir" under "See also" section redirect to non existing page

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#473]
Link under "See also" redirects to a non existing gh article.

**Repro steps**:
1. Go to https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/chdir-statement
2. Navigate to the "See also" section
3. Click on the "CurDir" link

**GH article**:
https://github.com/OfficeDev/VBA-content/blob/live/VBA/Language-Reference-VBA/articles/chdir-statement.md

**Actual results**:
Link redirects to non existing page
**Expected results**:
Link redirects to a valid page

![curdir](https://user-images.githubusercontent.com/16706698/36672578-109637fe-1b00-11e8-96e5-004c18e0d84e.png)

**Comment by lindalu-MSFT** [comment]
Fixed.
