### ISSUE TITLE
Comment.Text method does not function as described

### ISSUE THREAD

**Issue by vknowles** [OfficeDev/VBA-content#478]
As mentioned in [this old blog post](http://bigdon-in-vbaland.blogspot.com/2013/02/excel-comments-part-2.html), the Overwrite parameter default appears to be True rather than False. Also, attempting to specify Overwrite:=True throws error 5, "Invalid procedure call or argument." At least, VBA in Excel 2013 works that way for me.

**Comment by lindalu-MSFT** [comment]
@vknowles Where do you see this defined incorrectly in our content? Please include the link to the documentation where the parameter default is incorrect. Thanks, lindalu

**Comment by lindalu-MSFT** [comment]
Hi @vknowles - thanks for letting us know! I assume you're referring to this topic?
[Comment.Text Method](https://msdn.microsoft.com/en-us/vba/excel-vba/articles/comment-text-method-excel)

I've asked a few colleagues to verify that the default parameter for Overwrite is incorrect, and I'll get back to you. 

Linda

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
