### ISSUE TITLE
Broken formatting - Metadata issue

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#496]
**Article URL:** https://msdn.microsoft.com/en-us/vba/excel-vba/articles/sparklinegroup-object-excel
**GitHub URL:** https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/sparklinegroup-object-excel.md

**Repro steps:**
 1. Open the article
 2. Check the Metadata section
   - there is a redundant space on first line " ---"

![gh_issue](https://user-images.githubusercontent.com/16706698/37905572-92ad3430-30ff-11e8-8e3e-bb4eacc17e89.PNG)

**Actual results:**
  Article displayed with broken layout
**Expected results:**
  Fix metadata section to display content properly on live site

**Comment by lindalu-MSFT** [comment]
@OfficeGSX Thanks, fixed.
