### ISSUE TITLE
Broken formatting - Metadata issue

### ISSUE THREAD

**Issue by OfficeGSX** [OfficeDev/VBA-content#522]
Article URL: https://msdn.microsoft.com/en-us/vba/excel-vba/articles/sparklinegroup-object-excel
GitHub URL: https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/sparklinegroup-object-excel.md

Repro steps:

Open the article
Check the Metadata section
there is a redundant space on first line " ---"
![37905572-92ad3430-30ff-11e8-8e3e-bb4eacc17e89](https://user-images.githubusercontent.com/16706698/38679117-2d73e034-3e63-11e8-96ae-cdf2d4ca608c.PNG)

Actual results:
Article displayed with broken layout
Expected results:
Fix metadata section to display content properly on live site

**Comment by OfficeGSX** [comment]
This issue was once reported in this GH issue:
https://github.com/OfficeDev/VBA-content/issues/496

Regards,

Jiri

**Comment by Linda-Editor** [comment]
Fixed. Ready to publish.

**Comment by lindalu-MSFT** [comment]
@Linda-Editor Just @ me when you make the fix so I can close the issue! Or feel free to @ me, then close it yourself. Cheers!

**Comment by Linda-Editor** [comment]
@lindalu-MSFT  - Thanks! I wasn't sure about that. :-)
