### ISSUE TITLE
Create Object examples does not function on a MAC

### ISSUE THREAD

**Issue by tommiyau** [OfficeDev/VBA-content#525]
The CreateObject examples with an application with late or early binding does not function on a MAC. Probably best to call it out as such. These capabilities have not functioned since version 15 on a MAC. Leaving the pages present is misleading that VBA is portable between MAC and Windows. These examples have not functioned MAC Office 2016 for over 15 months.

**Comment by lindalu-MSFT** [comment]
@tommiyau Thanks for pointing this out. Will track down the topics and make a note! I appreciate your help. (Or feel free to make the updates and create a Pull Request!)

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
