### ISSUE TITLE
Links broken for chm downloads

### ISSUE THREAD

**Issue by GustavBrock** [OfficeDev/VBA-content#541]
All the links for the chm downloads, for example:
https://github.com/OfficeDev/VBA-content/blob/offline-docs/VBA/Offline-Docs/ACVBACon.chm 
are broken because the offline folder is gone.

Thus, also the readme.md file here is outdated:
https://github.com/OfficeDev/VBA-content/tree/master/VBA/Offline-Docs

**Comment by lindalu-MSFT** [comment]
@GustavBrock Thanks for finding this. I'll search for the chm download URLS and fix or delete them, once I figure out where the CHMs live now!

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
