### ISSUE TITLE
MS Access Method error(Average) in greek

### ISSUE THREAD

**Issue by mhackeras** [OfficeDev/VBA-content#544]
I have come across a bug in ms office - access 2016. Average doesnt work if method is called - written in greek. (Μέσος_Όρος) it is the method in greek language. Old access versions worked like a charm.

**Comment by lindalu-MSFT** [comment]
@mhackeras Thanks for reporting this. I will pass this on to the devs.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
