### ISSUE TITLE
opentextfile-method.md: the ForWriting constant isn't documented consistently

### ISSUE THREAD

**Issue by dhgutteridge** [OfficeDev/VBA-content#549]
In the opentextfile-method.md file, the code sample contains a reference to a ForWriting constant, but the "iomode" documentation in the tables above the code sample doesn't mention it at all. I'm confused by this: ForWriting (constant value 2) works perfectly fine for me with VBA in Excel 2013 and with Windows Script Host version 5.8. This constant is also documented elsewhere on pages scattered across the web, including other Microsoft pages. Was this purposefully (but incompletely) left out of the documentation for some reason? (If not, I can always submit a patch myself.)

**Comment by lindalu-MSFT** [comment]
@dhgutteridge Hi, can you provide me the URL to the documentation topic you're looking at? I see [this ](https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/opentextfile-method)when Iook at OpenTextFile Method.

**Comment by dhgutteridge** [comment]
Hi @lindalu-MSFT,

Yes, that's exactly the URL I'm talking about. If you look at the code example at the bottom of the page, note that it references a ForWriting constant ("iomode" value 2) that's not documented elsewhere in the page. The code example is out of sync with the tables above.

Constant 2 for "iomode" works fine for me. I'm not sure why it's not referenced in the tables.

Compare also with older Microsoft documentation on the same topic, e.g. [https://technet.microsoft.com/en-us/library/ee198715.aspx](https://technet.microsoft.com/en-us/library/ee198715.aspx), where you'll see this constant value is explicitly discussed.

**Comment by dhgutteridge** [comment]
Hi @lindalu-MSFT,

I've opened this as pull #556. (Like I said, I'm assuming the ForWriting reference wasn't deliberately omitted, since it works for me, and has been previously documented by Microsoft.)

**Comment by lindalu-MSFT** [comment]
Thanks @dhgutteridge I appreciate you bringing this to our attention! I merged this PR, but then I forgot that the content is in "freeze" right now. It may be a couple weeks before this update appears.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
