### ISSUE TITLE
Relationships between objects and their methods/properties are not easily discoverable in some documentation

### ISSUE THREAD

**Issue by dhgutteridge** [OfficeDev/VBA-content#550]
In the current form in which various objects and such are documented, their interrelationships aren't really discoverable. For instance, when referencing the TextStream object ([https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/textstream-object.md](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/textstream-object.md)), nowhere in it can one find that it exposes properties, such as AtEndOfStream ([https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/atendofstream-property.md](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Language-Reference-VBA/articles/atendofstream-property.md)).

Compare with older documentation from Microsoft still available online:

[https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/312a5kbt%28v%3dvs.84%29](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/312a5kbt%28v%3dvs.84%29)

Note in the URL above there are specific sections provided with links to associated methods and properties of TextStream.

Associated methods and properties also have reciprocal links in this older documentation, e.g.:

[https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/ffk3x3bw(v=vs.84)](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/windows-scripting/ffk3x3bw(v=vs.84))

(See "Applies To" in this second example.)

**Comment by lindalu-MSFT** [comment]
This is a common issue that gets reported. We need to figure out how to improve discoverability for our documentation!

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
