### ISSUE TITLE
Workbook.LinkInfo's param type in declaration and value's type in the example aren't different

### ISSUE THREAD

**Issue by frankcrc** [OfficeDev/VBA-content#574]
here is the [link](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/workbook-linkinfo-method-excel.md).
I found the third param of LinkInfo is declare as **XlLinkInfoType**, but in the example, it uses xlOleLinks, which is a value of **XlLink**.

**Comment by lindalu-MSFT** [comment]
@frankcrc Thank you for finding this! I updated the example to use the correct value, xlLinkInfoOLELinks. The change will be merged shortly.

**Comment by frankcrc** [comment]
@lindalu-MSFT isn't xlLinkTypeOLELinks?

**Comment by lindalu-MSFT** [comment]
@frankcrc [XlLinkInfoType Enumeration (Excel)](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Excel-VBA/articles/xllinkinfotype-enumeration-excel.md)
