### ISSUE TITLE
Comparing anything with Null results in Null instead of True or False

### ISSUE THREAD

**Issue by SiemEik** [OfficeDev/VBA-content#581]
From MS Access 2016, in the VBA Direct window (Ctrl+G), typing 'print 1<>2' will result in printing "True", but 'print 1<>Null' or 'print 1=Null'  will both result in Null, which used to result in True/False in previous versions. This means having tests like this in if-statements results in the script taking the wrong route. A very damaging bug if you're used to comparing text boxes that also can be empty (Null). Of course the Vartype test can solve this, but that means you have to go through all the code and redo all testing.

print 1<>2
True
print 1<>Null
Null
print 1=Null
Null
print Null=Null
Null

This bug is new in Microsoft Access 2016 MSO (16.0.9330.2073) 32-bits.

**Comment by lindalu-MSFT** [comment]
@SiemEik Thanks for pointing this out. I'll try to track down an Access writer to investigate. Can you provide a link to documentation that references this?

**Comment by TheSmileyCoder** [comment]
I am fairly sure it has always been like this. Comparing with null yields null. I have checked that the print behaviour you describe above is consistent with 2013 (and I believe earlier versions as well, but don't have a VM handy)

**Comment by Kagre** [comment]
Print IsNull(Null)

**Comment by Kagre** [comment]
or if you prefer

```vb
Print Nz(1 <> Null, True)
Print Nz(1 <> Null, False)
```

**Comment by Kagre** [comment]
also input boxes have empty strings not Null see:
https://msdn.microsoft.com/en-us/vba/language-reference-vba/articles/inputbox-function
```vb
Print InputBox("Enter Nothing") = ""
```

and form textbox controls in 2013 return null when empty but the VBA throws an error dialogue:

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
