### ISSUE TITLE
MsoTriState is clearly not a tri-state value

### ISSUE THREAD

**Issue by poizan42** [OfficeDev/VBA-content#586]
A lot can be said about this abomination, but the [documentation](https://github.com/OfficeDev/VBA-content/blob/master/VBA/Office-Shared-VBA/articles/msotristate-enumeration-office.md) right now states "Specifies a tri-state value.", which is factually wrong since only msoTrue and msoFalse are supported values.

**Comment by lindalu-MSFT** [comment]
@poizan42 Sadly, you are 100% correct. In this case,  there are only two logical meanings expressed by MsoTriState (tri, meaning 3, right?) which actually has 5 values! Only 2 of them are supported, msoFalse and msoTrue. I wish I could tell you that someone will take ownership and fix this! I will keep this issue open and at least see if I can find out WHY it's like this and hopefully improve upon the documentation. Thanks for making my day. lindalu

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
