### ISSUE TITLE
Bad link in "Revisions object"

### ISSUE THREAD

**Issue by tantale** [OfficeDev/VBA-content#6]
Hi,

In the **Revision object** (7f267a64-885a-cb4c-008a-e8545cea94d2.md) and **Revision Object Members** (../97eb185c-125a-1c5f-6f54-157fd5bbf355.md) articles:

The link **Revision object** point to **SmartArtLayout Object** (../f8d9db83-86f7-4830-096d-5d15368ab6b1.md). The target article should be "e6f64467-a438-88f1-60f9-975365a1430e.md".

Could you fix that?

**Comment by Lauragra** [comment]
Thank you for identifying the error. I have made the fix to both files.
