### ISSUE TITLE
Macintosh Users - Can't detect Office Add-ins installed

### ISSUE THREAD

**Issue by arana2** [OfficeDev/VBA-content#608]
I have a VBA script that is able to detect the Excel add-ins installed (Tools -> Excel Add-ins..)
<img width="380" alt="screen shot 2018-07-19 at 9 11 10 am" src="https://user-images.githubusercontent.com/38359810/42947633-c6b9b820-8b3b-11e8-842c-1bd3652e0497.png">

but unable to detect my Office Add-ins installed:
<img width="276" alt="screen shot 2018-07-19 at 10 07 46 am" src="https://user-images.githubusercontent.com/38359810/42947698-e2b1165e-8b3b-11e8-9797-44699a8d903c.png">

Is there a way to reference the Office Add-ins installed?

Here is my code for reference:

```
flag = 0
If InStr(Application.OperatingSystem, "Macintosh") Then
  For Each ad In Application.AddIns
    MsgBox ad.Name
        If InStr(1, ad.Name, "Vena", vbTextCompare) Then
            MsgBox "Vena add-in is installed."
            flag = 1
            Exit For
        End If
        Next
        If flag = 0 Then
            MsgBox "Vena add-in is not installed."
        End If
End If
```

**Comment by arana2** [comment]
Hello @ForNeVeR , @darraghbuckley , @yinaa , @darvasd , @lcorneliussen 
Hoping you can point me in the right direction.

**Comment by arana2** [comment]
@unpluggedk - hoping to get some information regarding this defect or if you're the right person to contact.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
