### ISSUE TITLE
MacID not working in Excel?

### ISSUE THREAD

**Issue by tofutim** [OfficeDev/VBA-content#633]
Excel 2016 on Mac. If I run
```
Sub Process_Click()
    Shell (MacID("MSWD"))
End Sub
```
I get
![image](https://user-images.githubusercontent.com/157766/43532345-b2123908-9566-11e8-9bdc-da9444d3088b.png)

Same with `Shell MacID("MSWD")`.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
