### ISSUE TITLE
Link to VBA Getting Started Not Working?

### ISSUE THREAD

**Issue by mscharlock** [OfficeDev/VBA-content#638]
Not sure if it's just me but the Getting Started link in this (https://github.com/OfficeDev/VBA-content/blob/master/VBA/VBA-Excel.md) doesn't seem to be working for me.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
