### ISSUE TITLE
Application.AfterDragDropOnSlide Event (PowerPoint)

### ISSUE THREAD

**Issue by MyGitHubHandle** [OfficeDev/VBA-content#653]
The event doesn't fire, it's clearly defective and doesn't appear to have every worked since it's release.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
