### ISSUE TITLE
Links in Readme.md are not valid

### ISSUE THREAD

**Issue by cindymeister** [OfficeDev/VBA-content#659]
I tried to find the chm files from the VBA-content Home (<code>) page by clicking on the links provided in the Readme. Those links give a 404 error: not found. It would be very helpful if the links were to be updated.

**Comment by lindalu-MSFT** [comment]
Thanks for your contribution! This content has migrated to [https://github.com/MicrosoftDocs/VBA-Docs](https://github.com/MicrosoftDocs/VBA-Docs). Please go to the new repo, and if you still see the issue occuring there, please open a brand new issue. Closing this issue now. Regards, lindalu
