### ISSUE TITLE
Intersect documentation needs clarification

### ISSUE THREAD

**Issue by buckleys78** [OfficeDev/VBA-content#93]
This function (perhaps Union as well?) crashes with a 1004 Run Time application error if the ranges are on different worksheets. This is not an unlikely error as a common use of this function includes the Target range from the Worksheet_Change event, which can be caused when VBA code updates cell(s) on a non-Active worksheet.

The documentation should note this constraint.

![application intersect runtime error](https://cloud.githubusercontent.com/assets/4951093/10925276/7fb9fc60-8241-11e5-8e39-5256292fb300.PNG)

**Comment by cronos2546** [comment]
https://github.com/OfficeDev/VBA-content/pull/142

**Comment by v-stnel** [comment]
Thank you for this comment. I have updated the topic for MSDN
