### ISSUE TITLE
DatabaseType does not default to "Microsoft Access"

### ISSUE THREAD

**Issue by ricardo-gr** [OfficeDev/VBA-content#94]
While testing this function, I found out you had to include this parameter with the "Microsoft Access" value in order to execute the function.

Otherwise, a 2057 error is thrown when trying to import/export/link to an Access database.

Example references of this issue:
http://www.pcreview.co.uk/threads/run-time-error-2507.3780386/
http://www.access-programmers.co.uk/forums/showthread.php?t=274207

**Comment by v-stnel** [comment]
Thank you for the input to this method. The DatabaseType parameter is not required for importing actions but is required for exporting and link data actions.
